### ISSUE TITLE
Migrate off of disqus

### ISSUE THREAD

**Issue by anarchivist** [anarchivist/matienzo.org#8]
...to staticman?

**Comment by sylvainmetayer** [comment]
Staticman is maybe not the best solution right now, as it seem there is some issue with Github API Rate limit. see eduardoboucas/staticman#222 for details, but you should think to self host it or find another solution.

You can find a comparative of existing solutions here : https://lisakov.com/projects/open-source-comments/

**Comment by VincentTam** [comment]
@sylvainmetayer The linked Staticman issue can be circumvented by migrating to GitLab, which imposes [an API rate limit of 600 req/min/**ip**](https://stackoverflow.com/a/46847101/3184351).
